"""empty message

Revision ID: 7f2c21a2ae02
Revises: 
Create Date: 2022-03-16 10:33:54.261675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2c21a2ae02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('administrador', sa.Boolean(), nullable=False),
    sa.Column('cambioPass', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Usuario', sa.Integer(), nullable=True),
    sa.Column('Categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['Usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.nombre'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('mes', sa.String(length=15), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('subcategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.nombre'], ),
    sa.ForeignKeyConstraint(['mes'], ['mes.nombre'], ),
    sa.ForeignKeyConstraint(['subcategoria'], ['subcategoria.nombre'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivo')
    op.drop_table('subcategoria')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('mes')
    op.drop_table('categoria')
    # ### end Alembic commands ###
